// Generated by js_of_ocaml
//# buildInfo:effects=disabled, kind=cmo, use-js-string=true, version=6.3.2

//# unitInfo: Provides: Dune__exe
//# shape: Dune__exe:[]
(function
  (globalThis){
   "use strict";
   var runtime = globalThis.jsoo_runtime;
   runtime.caml_register_global(0, [0], "Dune__exe");
   return;
  }
  (globalThis));

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiLnBhcnNlcl93ZWIuZW9ianMvanNvby9kdW5lX19leGUuY21vLmpzIiwic2VjdGlvbnMiOlt7Im9mZnNldCI6eyJsaW5lIjo4LCJjb2x1bW4iOjB9LCJtYXAiOnsidmVyc2lvbiI6MywiZmlsZSI6Ii5wYXJzZXJfd2ViLmVvYmpzL2pzb28vZHVuZV9fZXhlLmNtby5qcyIsInNvdXJjZXMiOlsiL2J1aWx0aW4vYmxhY2tib3gubWwiXSwic291cmNlc0NvbnRlbnQiOlsiKCogZ2VuZXJhdGVkIGNvZGUgKikiXSwibmFtZXMiOlsicnVudGltZSJdLCJtYXBwaW5ncyI6Ik9BQUFBLFVBQUEiLCJpZ25vcmVMaXN0IjpbMF19fV19
