// Generated by js_of_ocaml
//# buildInfo:effects=disabled, kind=cmo, use-js-string=true, version=6.3.2

//# unitInfo: Provides: Dune__exe__Parser_web
//# unitInfo: Requires: Dune__exe__Parser_core, Js_of_ocaml__Js
//# shape: Dune__exe__Parser_web:[]
(function
  (globalThis){
   "use strict";
   var
    runtime = globalThis.jsoo_runtime,
    global_data = runtime.caml_get_global_data(),
    Dune_exe_Parser_core = global_data.Dune__exe__Parser_core,
    Js_of_ocaml_Js = global_data.Js_of_ocaml__Js;
   function parse_english_js(sentence){
    var
     sentence$0 = runtime.caml_string_of_jsstring(sentence),
     result = Dune_exe_Parser_core[285].call(null, sentence$0);
    return runtime.caml_jsstring_of_string(result);
   }
   Js_of_ocaml_Js[50].call(null, "parseEnglish", parse_english_js);
   runtime.caml_register_global(3, [0], "Dune__exe__Parser_web");
   return;
  }
  (globalThis));

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiLnBhcnNlcl93ZWIuZW9ianMvanNvby9kdW5lX19leGVfX1BhcnNlcl93ZWIuY21vLmpzIiwic2VjdGlvbnMiOlt7Im9mZnNldCI6eyJsaW5lIjoxMCwiY29sdW1uIjowfSwibWFwIjp7InZlcnNpb24iOjMsImZpbGUiOiIucGFyc2VyX3dlYi5lb2Jqcy9qc29vL2R1bmVfX2V4ZV9fUGFyc2VyX3dlYi5jbW8uanMiLCJzb3VyY2VzIjpbIi9idWlsdGluL2JsYWNrYm94Lm1sIiwiL3dvcmtzcGFjZV9yb290L3BhcnNlcl93ZWIubWwiXSwic291cmNlc0NvbnRlbnQiOlsiKCogZ2VuZXJhdGVkIGNvZGUgKikiLCJvcGVuIEpzX29mX29jYW1sXG5cbmxldCBwYXJzZV9lbmdsaXNoX2pzIChzZW50ZW5jZSA6IEpzLmpzX3N0cmluZyBKcy50KSA6IEpzLmpzX3N0cmluZyBKcy50ID1cbiAgbGV0IHNlbnRlbmNlID0gSnMudG9fc3RyaW5nIHNlbnRlbmNlIGluXG4gIGxldCByZXN1bHQgPSBQYXJzZXJfY29yZS5wYXJzZV9lbmdsaXNoX2Zvcl93ZWIgc2VudGVuY2UgaW5cbiAgSnMuc3RyaW5nIHJlc3VsdFxuXG5sZXQgKCkgPVxuICBKcy5leHBvcnQgXCJwYXJzZUVuZ2xpc2hcIiBwYXJzZV9lbmdsaXNoX2pzIl0sIm5hbWVzIjpbInJ1bnRpbWUiLCJnbG9iYWxfZGF0YSIsIkR1bmVfZXhlX1BhcnNlcl9jb3JlIiwiSnNfb2Zfb2NhbWxfSnMiLCJwYXJzZV9lbmdsaXNoX2pzIiwic2VudGVuY2UiLCJyZXN1bHQiXSwibWFwcGluZ3MiOiJJQUFBQSxVQUFBO0FBQUEsSUFBQUMsY0FBQTtBQUFBLElBQUFDLHVCQUFBO0FBQUEsSUFBQUMsaUJBQUE7QUFBQSxZQUFBQyxpQkFBQUM7QUFBQUE7QUFBQUEsS0FBQUEsYUNHaUI7QUFBQSxLQUFBQyxTQUNGO0FBQUEsSUFDYiw4Q0FBZ0I7QUFBQTtBQUFBLEdBR2hCO0FBQUEsR0FBeUM7QUFBQTtBQUFBLEVEUjNDIiwiaWdub3JlTGlzdCI6WzBdfX1dfQ==
