from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LEXICON = ROOT / "lexicon"
OUT = Path(__file__).resolve().parent / "lexicon_generated.ml"

CATEGORIES = [
    "determiners",
    "wh_determiners",
    "pronouns",
    "nouns",
    "adjectives",
    "adverbs",
    "verbs",
    "participles",
    "gerunds",
    "auxiliaries",
    "modals",
    "tense_words",
    "prepositions",
    "complementizers",
    "question_auxiliaries",
    "wh_question_auxiliaries",
    "wh_prepositions",
    "coordinators",
    "trace_words",
    "numbers",
    "units",
    "currencies",
]

def read_words(category):
    path = LEXICON / f"{category}.txt"
    if not path.exists():
        return []
    words = []
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip().lower()
        if not line or line.startswith("#"):
            continue
        words.append(line)
    return sorted(set(words))

def ocaml_string(s):
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'

with OUT.open("w", encoding="utf-8") as f:
    f.write("(* Auto-generated by generate_lexicon_ml.py. Do not edit by hand. *)\n\n")
    for category in CATEGORIES:
        words = read_words(category)
        f.write(f"let {category} = [\n")
        for word in words:
            f.write(f"  {ocaml_string(word)};\n")
        f.write("]\n\n")

print(f"Wrote {OUT}")
